name: "Prepare Python environment"
description: "Set up Python and install dependencies"
runs:
  using: "composite"
  steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e
      with:
        python-version: 3.11
    - name: Install Poetry
      shell: bash
      run: curl -sSL https://install.python-poetry.org | python3 -
    - name: Install dependencies
      shell: bash
      run: poetry install
