name: prediction-market-agent

plugins:
  - name: foundry

default_ecosystem: gnosis

node:
  gnosis:
    mainnet:
      uri: https://rpc.gnosischain.com


networks:
  custom:
     - name: mainnet                   # Required
       chain_id: 100                   # Required
       ecosystem: gnosis
       base_ecosystem_plugin: ethereum
       default_provider: node

gnosis:
  default_network: gnosis_fork

foundry:
  host: http://localhost:8545/
  fork:
    gnosis:
      mainnet:
        upstream_provider: node
